### ISSUE TITLE
Crash on world generation w/ WWOO (Feature cycle bug)

### ISSUE THREAD

**Issue by Tempest-5ky** [mrsterner/Cultural-Delights-Fabric#12]
Hey! Server crashes when generating chunks due to a misplaced feature cycle, detailed here: https://mclo.gs/3Wdy0dB

The incompatibility seems to be with this mod: https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld

I am also sending a bug report there, but the issue would seem to be on this end. Minecraft version is Fabric 1.19.2, using the most recent release of this mod (1.14.9)

**Comment by RealKnoblauchbrot** [comment]
Same here. Also using William Wythers Overhauled Overworld and I am experiencing the same issue on version 1.20.1 (Quilt not Fabric).

Exact version: 0.14.10+1.20.1

**Comment by mrsterner** [comment]
Dont know why its happening

**Comment by mrsterner** [comment]
Jk might have figured out a solution

**Comment by jukarr** [comment]
This is, unfortunately, still an issue on 1.19.2
