### ISSUE TITLE
1.20.1 — Avocado leaves don't decay, avocado bundles don't generate on avocado trees, and I cannot right-click avocado bundles to get avocados (I have to break the bundle block).

### ISSUE THREAD

**Issue by viedemarli** [mrsterner/Cultural-Delights-Fabric#19]
### Cultural Delights version: 
0.14.11+1.20.1
### Fabric/Quilt Version: 
0.21.1 (Quilt)
### Issue
I've let three trees grow from their avocado pits and none of the three bore bundles—they only seem to grow if you bone-meal the sapling. When the tree does grow, leaves don't decay when the wood is broken and instead remain, having to be manually broken. They do not drop anything if you break them, either. I copied over the leaves fix that someone else made and committed on here, but that did not seem to fix the issue with the loot tables or decay. 

As for the bundles themselves, they don't seem to work the way they are intended, I think? I've seen around that you have to right-click on bundles to gather avocados, but right clicking doesn't seem to work and the only way to get avocados is to break the bundles themselves. Which is fine for me, it isn't a problem to break and replant the trees to make more because I already do that with all of the trees I plant (I have cinnamon trees from I think Expanded Delight and of course vanilla trees for logs and things). 

I'm not sure what I'm doing wrong or if it's an issue with this version of Cultural Delights, but I figured I'd throw it out there so it's in an official bug report in case anyone else is having this problem besides those I've seen on other places! I also can't seem to do any of these things on Fabric, either, so I'm certain it isn't Quilt's fault (I have two versions because I had an issue with a different mod that was resolved; they suggested trying on Fabric first to make sure it wasn't an issue with Quilt so I've just kind of adopted that into my own bug-report thing, since I know Quilt is slightly different from Fabric, though it can run most Fabric mods).

**Comment by NoahSlocombe** [comment]
I am also having this issue, exactly as you describe.

**Comment by mrsterner** [comment]
Ah, fabric version was a lil bit behind, fixed
