### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [mrsterner/Cultural-Delights-Fabric#21]
Compatibility for the new Farmer's Delight port:

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated?

It offers more support for a better port which is more faithful to the original mod on Forge, and is cleaner internally and has less bugs.

**Comment by mpustovoi** [comment]
Done

**Comment by NolanHewitt** [comment]
Some recipes seem to be broken in the new version such as the creamed corn, chicken taco, fish taco, spicy curry, chicken roll, rice ball, and the mutton sandwich. Seems to be something to do with the tags
