### ISSUE TITLE
egg roll recipe bug with refabricated

### ISSUE THREAD

**Issue by Joshua-z-Luo** [mrsterner/Cultural-Delights-Fabric#23]
"tag": "c:foods/cooked_meats/cooked_eggs" is used is farmers delight refabricated

"tag": "c:cooked_eggs" is used in cultural delights recipes.

I think this might cause a bug with the crafting of the recipes as I am unable to craft the egg roll when using the refabricated cultural delights version.

**Comment by Kaylielotl** [comment]
it seems like a similar (or the same) bug affects the mutton sandwich recipe, there are probably several others affected as well

**Comment by mrsterner** [comment]
fixed
