### ISSUE TITLE
Recipe missing components with Farmer's Delight [Refabricated]

### ISSUE THREAD

**Issue by AdrianaXL** [mrsterner/Cultural-Delights-Fabric#24]
A lot of the recipes from this mod are outdated when using the Refabricated version (example: using "c:cooked_pork" instead of "c:foods/cooked_meats/cooked_pork") and as a result, most of the recipes are missing their components and cannot be crafted.

**Comment by TheGamerCanine** [comment]
I wanted to boost this as well, I noticed a number of wraps and sandwiches that require meats just don't have them in the recipe

**Comment by mrsterner** [comment]
Ah ill fix it
