### ISSUE TITLE
[v1.0.4 -- 1.20.1] Eggplant patches generating incorrectly + Fix

### ISSUE THREAD

**Issue by Vwriter** [mrsterner/Cultural-Delights-Fabric#29]
I found no eggplants or corn in my world when playing with this mod, 
so I tried placing Cultural Delights' wild crop patches via commands to test if they could be generated in the first place, and then I discovered that **placing specifically the wild eggplant patch feature does nothing.** 
After messing around with the mod's files I found the reason why:

In the file `"culturaldelights\worldgen\configured_feature\patch_wild_eggplants.json"`, line 11, it says:

`"Name": "culturaldelights:wild_eggplant"`,

which is actually incorrect, and after I replaced it with

`"Name": "culturaldelights:wild_eggplants"`,

The eggplant patches started generating normally.

[patch_wild_eggplants.json](https://github.com/user-attachments/files/16117090/patch_wild_eggplants.json)

**Comment by mrsterner** [comment]
Shesh, ill fix

**Comment by Vwriter** [comment]
> Shesh, ill fix

I have forked your repo and fixed this and some more stuff. Everything seems to work properly now.
https://github.com/Vwriter/Cultural-Delights-Fabric/tree/1.20.1-refabricated-fixes

**Comment by Vwriter** [comment]
though I only touched the 1.20.1 refabricated branch

**Comment by mrsterner** [comment]
Ah i see, thank you
