### ISSUE TITLE
[Bug] Selection box for Exotic Roll Medley is huge

### ISSUE THREAD

**Issue by kingkuys2123** [mrsterner/Cultural-Delights-Fabric#3]
Minecraft 1.19.2 
Fabric 0.14.12
Cultural Delights 0.14.4

![2023-01-11_22 24 33](https://user-images.githubusercontent.com/114457180/211984904-b308acde-aebd-4f41-b0b7-6d7e9c200e61.png)

**Comment by mrsterner** [comment]
fixed in 0.14.6

**Comment by kingkuys2123** [comment]
@mrsterner, the upper part is still there  

![2023-01-13_09 03 14](https://user-images.githubusercontent.com/114457180/212213192-0e5c0db7-616a-46a5-a6b4-57075b4fffd0.png)
